# Generated by Django 5.0.6 on 2024-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartments', '0003_remove_student_compartment_compartment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartment',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='compartment',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
