# Generated by Django 5.0.6 on 2024-06-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartments', '0002_remove_compartment_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='compartment',
        ),
        migrations.AddField(
            model_name='compartment',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compartments.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='compartment',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
